version: "3.9"

services:
  web:
    image: "nginx:alpine"
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - ./www:/var/www
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf

  php:
    build: .
    volumes:
      - ./www:/var/www
    healthcheck:
      test: curl -f http://nginx | grep works || exit 1
      interval: 1s
      timeout: 10s
